export const LIKE_DISH = "LIKE_DISH";
export const DISLIKE_DISH = "DISLIKE_DISH";
export const LIKE_DISH_ASYNC = "LIKE_DISH_ASYNC";
export const DISLIKE_DISH_ASYNC = "DISLIKE_DISH_ASYNC";
export const GET_DISHES = "GET_DISHES";
export const GET_DISHES_ASYNC = "GET_DISHES_ASYNC";
